### ISSUE TITLE
luigi.rpc.RPCError: Errors (3 attempts) when connecting to remote scheduler 'http://localhost:8082'

### ISSUE THREAD

**Issue by bhandari-nitin** [hopelessoptimism/data-engineering-101#9]
When running ml-pipeline.py with the command:

 python ml-pipeline.py Vectorize --input-dir text
 
gets the following error:

DEBUG: Checking if InputText(filename=text/article548.txt) is complete
DEBUG: Checking if InputText(filename=text/article574.txt) is complete
DEBUG: Checking if InputText(filename=text/article212.txt) is complete
DEBUG: Checking if InputText(filename=text/article206.txt) is complete
DEBUG: Checking if InputText(filename=text/article560.txt) is complete
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/add_task (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1185d6ad0>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO: Retrying attempt 2 of 3 (max)
INFO: Wait for 30 seconds
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118e13bd0>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO: Retrying attempt 2 of 3 (max)
INFO: Wait for 30 seconds
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/add_task (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118e13e50>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO: Retrying attempt 3 of 3 (max)
INFO: Wait for 30 seconds
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118e13c50>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO: Retrying attempt 3 of 3 (max)
INFO: Wait for 30 seconds
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/add_task (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118e139d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
ERROR: Luigi unexpected framework error while scheduling Vectorize(input_dir=text, evaluate=False)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 763, in add
    for next in self._add(item, is_complete):
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 881, in _add
    accepts_messages=task.accepts_messages,
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 593, in _add_task
    self._scheduler.add_task(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/luigi/scheduler.py", line 122, in rpc_func
    return self._request('/api/{}'.format(fn_name), actual_args, **request_args)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 162, in _request
    page = self._fetch(url, body)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 154, in _fetch
    last_exception
RPCError: Errors (3 attempts) when connecting to remote scheduler 'http://localhost:8082'
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 142, in _fetch
    response = self._fetcher.fetch(full_url, body, self._connect_timeout)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 95, in fetch
    resp = self.session.get(full_url, data=body, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8082): Max retries exceeded with url: /api/ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x118e58d50>: Failed to establish a new connection: [Errno 61] Connection refused',))
WARNING: Failed pinging scheduler
INFO: Worker Worker(salt=477878290, workers=1, host=Nitins-MacBook-Pro.local, username=nitin, pid=33269) was stopped. Shutting down Keep-Alive thread
Traceback (most recent call last):
  File "ml-pipeline.py", line 217, in <module>
    luigi.run()
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 194, in run
    luigi_run_result = _run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 211, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python2.7/site-packages/luigi/interface.py", line 171, in _schedule_and_run
    success &= worker.add(t, env_params.parallel_scheduling, env_params.parallel_scheduling_processes)
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 763, in add
    for next in self._add(item, is_complete):
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 881, in _add
    accepts_messages=task.accepts_messages,
  File "/usr/local/lib/python2.7/site-packages/luigi/worker.py", line 593, in _add_task
    self._scheduler.add_task(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/luigi/scheduler.py", line 122, in rpc_func
    return self._request('/api/{}'.format(fn_name), actual_args, **request_args)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 162, in _request
    page = self._fetch(url, body)
  File "/usr/local/lib/python2.7/site-packages/luigi/rpc.py", line 154, in _fetch
    last_exception
luigi.rpc.RPCError: Errors (3 attempts) when connecting to remote scheduler 'http://localhost:8082'

**Comment by bhandari-nitin** [comment]
Never mind, worked after running:
`luigid --port 8082`

**Comment by yefovar** [comment]
I used your solution, thank you mate!
